### ISSUE TITLE
Errors when using in Sapper

### ISSUE THREAD

**Issue by MTyson** [typewriter-editor/typewriter#64]
I am running into errors with setting up typewriter in a sapper app.  For example, when I run this import:

`import { Editor } from 'typewriter-editor';`

I get the error:

```
C:\Users\Matt\projects\toprank\node_modules\typewriter-editor\lib\doc\TextDocument.js:241
window.AttributeMap = AttributeMap_1.default;
^
ReferenceError: window is not defined
```

I know this is because of SSR trying to resolve the import during server-side (non-browser) and running into a ref to window.

Is there docs on this? Workaround? 

I think if the code would do a check (if (window){...}) then this would be avoided.

**Comment by taylorhadden** [comment]
I am also having this issue when trying to use TextDocument in tests and main-side in an electron application. I can poke this and see what pops.

**Comment by taylorhadden** [comment]
If I remove that `(window as any).AttributeMap` line, I pretty much immediately hit issues with NodeFilter not being defined in walker.ts.

These rendering files are being invoked because index.ts pulls in and reexports everything. Therefor, importing one thing imports all things.

An immediate way to resolve this is to import only exactly what you need from the various directories in "typewriter-editor/lib/...". This will work.

However, I find value in being able to use a "on-stop-shop" import call. e.g.

```
// Consumer.ts
import { TextDocument, Line, Delta } from 'typewriter-editor/lib/Backend'

// Backend.ts
import TextDocument from './doc/TextDocument'
import Line from './doc/Line'
import Delta from './delta/Delta'

export { TextDocument, Line, Delta }
```

(I came up with "Backend" after ~2 seconds of thinking. Would love ideas on a superior name.)

Another option could be to add an `index.ts` file for the doc and delta directories. That would at least let `TextDocument` and `Line` be imported in a single line.

All in all, it's pretty trivial to set up my *own* utility importer so my imports can be one line, and not that hard to import the things you need over a handful of lines. I don't really have strong opinions on this.

I will get a pull request up to remove that line shortly.

**Comment by taylorhadden** [comment]
I realized I had not tested importing `Editor` itself from within Node. Event when importing Editor directly and with that TextDocument line removed, this does *not* work. The new offender is the missing `Event` type that `modules/decorations.ts` relies on.

**Comment by taylorhadden** [comment]
I have a PR up to fix the TextEditor import issue at the very least: #68

**Comment by taylorhadden** [comment]
@jacwright, I don't know if you meant it to, but the commit with 0.6.21 does not contain this fix.
